### PR TITLE
virtualenv uses bin/ not Scripts/

### PR DESCRIPTION
**Pull request by crowell**

### CODE REVIEW

**Comment by Kerrigan29a** [comment]
In Windows, all the scripts are in the Scripts folder, there's no bin folder.

**Comment by Kerrigan29a** [comment]
"Scripts" folder is an specific feature [for Windows](https://virtualenv.pypa.io/en/latest/userguide.html#windows-notes) so this code should work:

``` python
folder = "Scripts" if os.name "nt" else "bin"
```

**Comment by crowell** [comment]
fixed to detect windows

**Comment by crowell** [comment]
ping?

**Comment by Kerrigan29a** [comment]
Sorry about the delay. I've been doing other things and I forgot about this.

And thanks for your time

**Pull request merged**
